---
- name: Configure Web Servers
  hosts: web_servers
  become: true

  roles:
    - role: web
      tags: [web]

- name: Configure Database Servers
  hosts: db_servers
  become: true

  roles:
    - role: db
      tags: [db]

- name: Configure File Servers
  hosts: file_servers
  become: true

  roles:
    - role: fileserver
      tags: [fileserver]
